config/routes.rb
Rails.application.routes.draw do
  # get 'static_pages/index'
  get 'static_pages/secret'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'static_pages#index'
  # get 'events/index'
  # get 'events/new'
  # get 'events/show'
  # get 'events/create'
  resources :events, only: [:index, :new, :show, :create]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances
  has_many :users, through: :attendances
  validates :start_date, presence: true, comparison: { greater_than: DateTime.now }
  validates :duration, presence: true, numericality: { divisible_by: 5, greater_than: 0 }
  validates :title, presence: true, length: 5..140
  validates :description, presence: true, length: 20..10000
  validates :price, presence: true, numericality: { greater_than: 0, less_than_or_equal_to: 10000 }
  validates :location, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send

  has_many :attendances
  has_many :events, through: :attendances

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
  end

  def show
  end

  def create
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
before_action :authenticate_user!, only: [:secret]

  def index
  end

  def secret
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<div class= "row justify-content-center">
  <% @events.each do |event| %>
    <div class="d-flex justify-content-center col-md-4 col-sm-6 my-4">
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Titre: <%= event.title %></h5>
          <% date = event.start_date %>
          <p class="card-text">Date: <%= date.strftime("%d-%m-%Y à %H:%M") %></p>
          <p class="card-text">Description: <%= event.description %></p>
          <p class="card-text">Location: <%= event.location %></p>

        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<p>views/events/new.html.erb</p>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="<%= events_path %>">Eventbrite</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Créer un événement</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown link
                </a>
                <% if current_user %>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Mon profil</a></li>
                  <li><a class="dropdown-item" href="<%= destroy_user_session_path %>">Se déconnecter</a></li>
                </ul>
                <% else %>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="<%= new_user_registration_path %>">S'inscrire</a></li>
                  <li><a class="dropdown-item" href="<%= new_user_session_path %>">Se connecter</a></li>
                </ul>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/static_pages/index.html.erb
<h1>Elle est moche cette page vide. Tiens, voilà du boudin.</h1>

<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>